config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :summon_details

  namespace :api do
    namespace :v1 do
      resources :friend_posts
      resources :summon_details
    end
  end
end

app/models/element.rb
class Element
  include Mongoid::Document

  field :name,          type: String
  field :icon_url,      type: String
end

app/models/friend_post.rb
class FriendPost
  include Mongoid::Document
  include Mongoid::Timestamps

  field :account_id,        type: String
  field :title,             type: String
  field :description,       type: String
end

app/models/summon_container.rb
class SummonContainer
  include Mongoid::Document

  field :uncap_level,         type: String

  belongs_to :summon_detail
end

app/models/summon_detail.rb
class SummonDetail
  include Mongoid::Document

  field :name,                type: String
  field :max_uncap,           type: String

  # aura
  field :aura,                type: String
  field :mlb_aura,            type: String
  field :flb_aura,            type: String

  # call
  field :call,                type: String
  field :mlb_call,            type: String
  field :flb_call,            type: String

  # pic url
  field :small_pic,           type: String
  field :medium_pic,          type: String
  field :large_pic,           type: String

  # flb pic url
  field :flb_small_pic,       type: String
  field :flb_medium_pic,      type: String
  field :flb_large_pic,       type: String

  belongs_to :element, optional: true

  module UncapType
    NORMAL = 'normal'
    MLB = 'mlb'
    FLB = 'flb'
  end

  before_update :set_max_uncap

  private
  def set_max_uncap
    if flb_aura.present? || flb_call.present? || flb_small_pic.present? || flb_medium_pic.present? || flb_large_pic.present?
      max_uncap = UncapType::NORMAL
    elsif mlb_aura.present? || mlb_call.present?
      max_uncap = UncapType::MLB
    else
      max_uncap = UncapType::FLB
    end
  end
end

app/controllers/api/v1/friend_posts_controller.rb
module Api
  module V1
    class FriendPostsController < ApplicationController
      # To allow only json request
      protect_from_forgery with: :null_session, if: Proc.new {|c| c.request.format.json? }

      def index
        posts = FriendPost.all
        render json: { posts: posts }, status: 200
      end

      def show
        post = FriendPost.where(id: params[:id]).first
        render json: { post: post }, status: 200
      end

      def create
        post = FriendPost.new(post_params)

        if post.save
          render json: {
            success: true,
            post_id: post.id
          }, status: 200
        else
          render json: {
            success: false,
            error_messages: post.errors.full_messages
          }, status: 400
        end
      end

      private

      def post_params
        params.require(:friend_post).permit(:account_id, :title, :description)
      end
    end
  end
end

app/controllers/api/v1/summon_details_controller.rb
module Api
  module V1
    class SummonDetailsController < ApplicationController
      def index

      end

      def show

      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/summon_details_controller.rb
class SummonDetailsController < ApplicationController
  def index
    @summons = SummonDetail.all
  end

  def new
    @summon = SummonDetail.new
  end

  def create
    @summon = SummonDetail.new(summon_params)

    if @summon.save
      flash[:success] = 'Create summon success'
      redirect_to summon_details_path
    else
      flash[:error] = @summor.errors.full_messages
      render :new
    end
  end

  def edit
    @summon = SummonDetail.where(id: params[:id]).first
  end

  def update
    @summon = SummonDetail.where(id: params[:id]).first
    if @summon.update(summon_params)
      flash[:success] = 'Update summon success'
      redirect_to summon_details_path
    else
      flash[:error] = @summor.errors.full_messages
      render :edit
    end
  end

  def destroy
    @summon = SummonDetail.where(id: params[:id]).first
    @summon.destroy

    flash[:success] = 'Delete summon success'
    redirect_to summon_details_path
  end

  private

  def summon_params
    params.require(:summon_detail).permit(:name, :aura, :mlb_aura, :flb_aura, :small_pic, :medium_pic, :large_pic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GbfFriendFinderBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/summon_details/_form.html.erb
<div>
  Name: <%= form.text_field :name %>
</div>
<div>
  Aura: <%= form.text_area :aura %>
</div>
<div>
  MLB Aura: <%= form.text_area :mlb_aura %>
</div>
<div>
  FLB Aura: <%= form.text_area :flb_aura %>
</div>
<%= image_tag @summon.small_pic || '', height: '50' %>
<div>
  Small Pic: <%= form.text_field :small_pic %>
</div>
<%= image_tag @summon.medium_pic || '', height: '150' %>
<div>
  Medium Pic: <%= form.text_field :medium_pic %>
</div>
<%= image_tag @summon.large_pic || '', height: '150' %>
<div>
  Large Pic: <%= form.text_field :large_pic %>
</div>

app/views/summon_details/edit.html.erb
<%= form_for @summon, url: { action: :update } do |f| %>
  <%= render partial: 'form', locals: { form: f } %>

  <%= f.submit 'Submit' %>
  <%= link_to 'Back', summon_details_path %>
<% end %>

app/views/summon_details/index.html.erb
<%= link_to 'Add Summon', new_summon_detail_path %>
<table border="1">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Element</th>
      <th colspan="2">Aura</th>
      <th>Small Pic</th>
      <th>Medium Pic</th>
      <th>Large Pic</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @summons.each_with_index do |summon, index| %>
      <tr>
        <td rowspan="3">
          <abbr title="<%= summon.id.to_s %>">
            <%= index %>
          </abbr>
        </td>
        <td rowspan="3"><%= summon.name %></td>
        <td rowspan="3"><%= summon.element&.name %></td>
        <td>0★</td>
        <td><%= summon.aura %></td>
        <td rowspan="3">
          <abbr title="<%= summon.small_pic %>">
            <%= image_tag summon.small_pic, height: '50' %><br/>
          </abbr>
        </td>
        <td rowspan="3">
          <abbr title="<%= summon.medium_pic %>">
            <%= image_tag summon.medium_pic, height: '50' %><br/>
          </abbr>
        </td>
        <td rowspan="3">
          <abbr title="<%= summon.large_pic %>">
            <%= image_tag summon.large_pic, height: '50' %><br/>
          </abbr>
        </td>
        <td rowspan="3"><%= link_to 'Edit', edit_summon_detail_path(summon) %></td>
        <td rowspan="3">
          <%= link_to 'Delete', summon_detail_path(summon), data: { confirm: 'Are you sure?' }, method: :delete %>
        </td>
      </tr>
      <tr>
        <td>3★</td>
        <td><%= summon.mlb_aura %>
      </tr>
      <tr>
        <td>4★</td>
        <td><%= summon.flb_aura %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/summon_details/new.html.erb
<%= form_for @summon, url: { action: :create } do |f| %>
  <%= render partial: 'form', locals: { form: f } %>

  <%= f.submit 'Submit' %>
  <%= link_to 'Back', summon_details_path %>
<% end %>